/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAuditLog {
  'id' : AuditLogId,
  'action' : string,
  'adminPrincipal' : Principal,
  'timestamp' : Timestamp,
  'details' : string,
  'targetId' : [] | [string],
}
export type AuditLogId = bigint;
export type DownloadTokenId = bigint;
export interface DownloadTokenView {
  'id' : DownloadTokenId,
  'token' : string,
  'expiresAt' : Timestamp,
  'isUsed' : boolean,
  'orderId' : OrderId,
  'downloadCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export type OrderId = bigint;
export type OrderStatus = { 'PendingVerification' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null };
export interface OrderView {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'rejectionReason' : [] | [string],
  'productId' : ProductId,
  'paymentProofBlob' : [] | [ExternalBlob],
  'updatedAt' : Timestamp,
  'buyerPrincipal' : Principal,
}
export type PaymentMethod = { 'ABL' : null } |
  { 'JazzCash' : null };
export type ProductCategory = { 'WebApp' : null } |
  { 'Plugin' : null } |
  { 'Script' : null } |
  { 'Template' : null } |
  { 'MobileApp' : null };
export type ProductId = bigint;
export interface ProductView {
  'id' : ProductId,
  'title' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'previewImageBlob' : [] | [ExternalBlob],
  'isActive' : boolean,
  'category' : ProductCategory,
  'fileStorageBlob' : [] | [ExternalBlob],
  'priceUsd' : bigint,
}
export type Timestamp = bigint;
export interface UserProfile {
  'displayName' : string,
  'isBlocked' : boolean,
  'createdAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminApproveOrder' : ActorMethod<[OrderId], string>,
  'adminCreateProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      ProductCategory,
      Array<string>,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    ProductId
  >,
  'adminDashboardStats' : ActorMethod<
    [],
    {
      'totalProducts' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'approvedOrders' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'adminGetUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'adminListAuditLogs' : ActorMethod<[], Array<AdminAuditLog>>,
  'adminListOrders' : ActorMethod<[], Array<OrderView>>,
  'adminRejectOrder' : ActorMethod<[OrderId, string], undefined>,
  'adminSeedProducts' : ActorMethod<[], undefined>,
  'adminSetProductActive' : ActorMethod<[ProductId, boolean], undefined>,
  'adminSetUserBlocked' : ActorMethod<[Principal, boolean], undefined>,
  'adminUpdateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      bigint,
      ProductCategory,
      Array<string>,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderView]>,
  'getProduct' : ActorMethod<[ProductId], [] | [ProductView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyDownloadTokens' : ActorMethod<[], Array<DownloadTokenView>>,
  'listMyOrders' : ActorMethod<[], Array<OrderView>>,
  'listProducts' : ActorMethod<[], Array<ProductView>>,
  'placeOrder' : ActorMethod<
    [ProductId, PaymentMethod, [] | [ExternalBlob]],
    OrderId
  >,
  'redeemDownloadToken' : ActorMethod<[string], [] | [ExternalBlob]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPaymentProof' : ActorMethod<[OrderId, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];