/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const OrderId = IDL.Nat;
export const ProductCategory = IDL.Variant({
  'WebApp' : IDL.Null,
  'Plugin' : IDL.Null,
  'Script' : IDL.Null,
  'Template' : IDL.Null,
  'MobileApp' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'createdAt' : Timestamp,
});
export const AuditLogId = IDL.Nat;
export const AdminAuditLog = IDL.Record({
  'id' : AuditLogId,
  'action' : IDL.Text,
  'adminPrincipal' : IDL.Principal,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'targetId' : IDL.Opt(IDL.Text),
});
export const OrderStatus = IDL.Variant({
  'PendingVerification' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'ABL' : IDL.Null,
  'JazzCash' : IDL.Null,
});
export const OrderView = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'paymentProofBlob' : IDL.Opt(ExternalBlob),
  'updatedAt' : Timestamp,
  'buyerPrincipal' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductView = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'previewImageBlob' : IDL.Opt(ExternalBlob),
  'isActive' : IDL.Bool,
  'category' : ProductCategory,
  'fileStorageBlob' : IDL.Opt(ExternalBlob),
  'priceUsd' : IDL.Nat,
});
export const DownloadTokenId = IDL.Nat;
export const DownloadTokenView = IDL.Record({
  'id' : DownloadTokenId,
  'token' : IDL.Text,
  'expiresAt' : Timestamp,
  'isUsed' : IDL.Bool,
  'orderId' : OrderId,
  'downloadCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminApproveOrder' : IDL.Func([OrderId], [IDL.Text], []),
  'adminCreateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ProductCategory,
        IDL.Vec(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [ProductId],
      [],
    ),
  'adminDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'pendingOrders' : IDL.Nat,
          'approvedOrders' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'adminGetUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'adminListAuditLogs' : IDL.Func([], [IDL.Vec(AdminAuditLog)], ['query']),
  'adminListOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
  'adminRejectOrder' : IDL.Func([OrderId, IDL.Text], [], []),
  'adminSeedProducts' : IDL.Func([], [], []),
  'adminSetProductActive' : IDL.Func([ProductId, IDL.Bool], [], []),
  'adminSetUserBlocked' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'adminUpdateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ProductCategory,
        IDL.Vec(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderView)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyDownloadTokens' : IDL.Func(
      [],
      [IDL.Vec(DownloadTokenView)],
      ['query'],
    ),
  'listMyOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
  'placeOrder' : IDL.Func(
      [ProductId, PaymentMethod, IDL.Opt(ExternalBlob)],
      [OrderId],
      [],
    ),
  'redeemDownloadToken' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPaymentProof' : IDL.Func([OrderId, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const OrderId = IDL.Nat;
  const ProductCategory = IDL.Variant({
    'WebApp' : IDL.Null,
    'Plugin' : IDL.Null,
    'Script' : IDL.Null,
    'Template' : IDL.Null,
    'MobileApp' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'createdAt' : Timestamp,
  });
  const AuditLogId = IDL.Nat;
  const AdminAuditLog = IDL.Record({
    'id' : AuditLogId,
    'action' : IDL.Text,
    'adminPrincipal' : IDL.Principal,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'targetId' : IDL.Opt(IDL.Text),
  });
  const OrderStatus = IDL.Variant({
    'PendingVerification' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'ABL' : IDL.Null,
    'JazzCash' : IDL.Null,
  });
  const OrderView = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Timestamp,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'paymentProofBlob' : IDL.Opt(ExternalBlob),
    'updatedAt' : Timestamp,
    'buyerPrincipal' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductView = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'previewImageBlob' : IDL.Opt(ExternalBlob),
    'isActive' : IDL.Bool,
    'category' : ProductCategory,
    'fileStorageBlob' : IDL.Opt(ExternalBlob),
    'priceUsd' : IDL.Nat,
  });
  const DownloadTokenId = IDL.Nat;
  const DownloadTokenView = IDL.Record({
    'id' : DownloadTokenId,
    'token' : IDL.Text,
    'expiresAt' : Timestamp,
    'isUsed' : IDL.Bool,
    'orderId' : OrderId,
    'downloadCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminApproveOrder' : IDL.Func([OrderId], [IDL.Text], []),
    'adminCreateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ProductCategory,
          IDL.Vec(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [ProductId],
        [],
      ),
    'adminDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'pendingOrders' : IDL.Nat,
            'approvedOrders' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'adminGetUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'adminListAuditLogs' : IDL.Func([], [IDL.Vec(AdminAuditLog)], ['query']),
    'adminListOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
    'adminRejectOrder' : IDL.Func([OrderId, IDL.Text], [], []),
    'adminSeedProducts' : IDL.Func([], [], []),
    'adminSetProductActive' : IDL.Func([ProductId, IDL.Bool], [], []),
    'adminSetUserBlocked' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'adminUpdateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ProductCategory,
          IDL.Vec(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderView)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyDownloadTokens' : IDL.Func(
        [],
        [IDL.Vec(DownloadTokenView)],
        ['query'],
      ),
    'listMyOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
    'placeOrder' : IDL.Func(
        [ProductId, PaymentMethod, IDL.Opt(ExternalBlob)],
        [OrderId],
        [],
      ),
    'redeemDownloadToken' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPaymentProof' : IDL.Func([OrderId, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };