/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    displayName: string;
    isBlocked: boolean;
    createdAt: Timestamp;
}
export interface AdminAuditLog {
    id: AuditLogId;
    action: string;
    adminPrincipal: Principal;
    timestamp: Timestamp;
    details: string;
    targetId?: string;
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type AuditLogId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type DownloadTokenId = bigint;
export interface ProductView {
    id: ProductId;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    previewImageBlob?: ExternalBlob;
    isActive: boolean;
    category: ProductCategory;
    fileStorageBlob?: ExternalBlob;
    priceUsd: bigint;
}
export interface DownloadTokenView {
    id: DownloadTokenId;
    token: string;
    expiresAt: Timestamp;
    isUsed: boolean;
    orderId: OrderId;
    downloadCount: bigint;
}
export type ProductId = bigint;
export type OrderId = bigint;
export interface OrderView {
    id: OrderId;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    rejectionReason?: string;
    productId: ProductId;
    paymentProofBlob?: ExternalBlob;
    updatedAt: Timestamp;
    buyerPrincipal: Principal;
}
export enum OrderStatus {
    PendingVerification = "PendingVerification",
    Approved = "Approved",
    Rejected = "Rejected"
}
export enum PaymentMethod {
    ABL = "ABL",
    JazzCash = "JazzCash"
}
export enum ProductCategory {
    WebApp = "WebApp",
    Plugin = "Plugin",
    Script = "Script",
    Template = "Template",
    MobileApp = "MobileApp"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminApproveOrder(orderId: OrderId): Promise<string>;
    adminCreateProduct(title: string, description: string, priceUsd: bigint, category: ProductCategory, tags: Array<string>, previewImageBlob: ExternalBlob | null, fileStorageBlob: ExternalBlob | null): Promise<ProductId>;
    adminDashboardStats(): Promise<{
        totalProducts: bigint;
        totalOrders: bigint;
        pendingOrders: bigint;
        approvedOrders: bigint;
        totalUsers: bigint;
    }>;
    adminGetUserProfile(user: Principal): Promise<UserProfile | null>;
    adminListAuditLogs(): Promise<Array<AdminAuditLog>>;
    adminListOrders(): Promise<Array<OrderView>>;
    adminRejectOrder(orderId: OrderId, reason: string): Promise<void>;
    adminSeedProducts(): Promise<void>;
    adminSetProductActive(id: ProductId, isActive: boolean): Promise<void>;
    adminSetUserBlocked(user: Principal, blocked: boolean): Promise<void>;
    adminUpdateProduct(id: ProductId, title: string, description: string, priceUsd: bigint, category: ProductCategory, tags: Array<string>, previewImageBlob: ExternalBlob | null, fileStorageBlob: ExternalBlob | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOrder(id: OrderId): Promise<OrderView | null>;
    getProduct(id: ProductId): Promise<ProductView | null>;
    isCallerAdmin(): Promise<boolean>;
    listMyDownloadTokens(): Promise<Array<DownloadTokenView>>;
    listMyOrders(): Promise<Array<OrderView>>;
    listProducts(): Promise<Array<ProductView>>;
    placeOrder(productId: ProductId, paymentMethod: PaymentMethod, paymentProofBlob: ExternalBlob | null): Promise<OrderId>;
    redeemDownloadToken(token: string): Promise<ExternalBlob | null>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPaymentProof(orderId: OrderId, paymentProofBlob: ExternalBlob): Promise<void>;
}
import type { AdminAuditLog as _AdminAuditLog, AuditLogId as _AuditLogId, ExternalBlob as _ExternalBlob, OrderId as _OrderId, OrderStatus as _OrderStatus, OrderView as _OrderView, PaymentMethod as _PaymentMethod, ProductCategory as _ProductCategory, ProductId as _ProductId, ProductView as _ProductView, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminApproveOrder(arg0: OrderId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveOrder(arg0);
            return result;
        }
    }
    async adminCreateProduct(arg0: string, arg1: string, arg2: bigint, arg3: ProductCategory, arg4: Array<string>, arg5: ExternalBlob | null, arg6: ExternalBlob | null): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateProduct(arg0, arg1, arg2, to_candid_ProductCategory_n8(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateProduct(arg0, arg1, arg2, to_candid_ProductCategory_n8(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async adminDashboardStats(): Promise<{
        totalProducts: bigint;
        totalOrders: bigint;
        pendingOrders: bigint;
        approvedOrders: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDashboardStats();
            return result;
        }
    }
    async adminGetUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListAuditLogs(): Promise<Array<AdminAuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAuditLogs();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAuditLogs();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListOrders(): Promise<Array<OrderView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectOrder(arg0: OrderId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectOrder(arg0, arg1);
            return result;
        }
    }
    async adminSeedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSeedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSeedProducts();
            return result;
        }
    }
    async adminSetProductActive(arg0: ProductId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetProductActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetProductActive(arg0, arg1);
            return result;
        }
    }
    async adminSetUserBlocked(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetUserBlocked(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetUserBlocked(arg0, arg1);
            return result;
        }
    }
    async adminUpdateProduct(arg0: ProductId, arg1: string, arg2: string, arg3: bigint, arg4: ProductCategory, arg5: Array<string>, arg6: ExternalBlob | null, arg7: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, arg1, arg2, arg3, to_candid_ProductCategory_n8(this._uploadFile, this._downloadFile, arg4), arg5, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, arg1, arg2, arg3, to_candid_ProductCategory_n8(this._uploadFile, this._downloadFile, arg4), arg5, await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<OrderView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<ProductView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMyDownloadTokens(): Promise<Array<DownloadTokenView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyDownloadTokens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyDownloadTokens();
            return result;
        }
    }
    async listMyOrders(): Promise<Array<OrderView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<ProductView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: ProductId, arg1: PaymentMethod, arg2: ExternalBlob | null): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, to_candid_PaymentMethod_n37(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, to_candid_PaymentMethod_n37(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async redeemDownloadToken(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemDownloadToken(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemDownloadToken(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPaymentProof(arg0: OrderId, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentProof(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentProof(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminAuditLog_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminAuditLog): AdminAuditLog {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_OrderView_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderView): Promise<OrderView> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_ProductView_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductView): Promise<ProductView> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderView]): Promise<OrderView | null> {
    return value.length === 0 ? null : await from_candid_OrderView_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductView]): Promise<ProductView | null> {
    return value.length === 0 ? null : await from_candid_ProductView_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AuditLogId;
    action: string;
    adminPrincipal: Principal;
    timestamp: _Timestamp;
    details: string;
    targetId: [] | [string];
}): {
    id: AuditLogId;
    action: string;
    adminPrincipal: Principal;
    timestamp: Timestamp;
    details: string;
    targetId?: string;
} {
    return {
        id: value.id,
        action: value.action,
        adminPrincipal: value.adminPrincipal,
        timestamp: value.timestamp,
        details: value.details,
        targetId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.targetId))
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    createdAt: _Timestamp;
    rejectionReason: [] | [string];
    productId: _ProductId;
    paymentProofBlob: [] | [_ExternalBlob];
    updatedAt: _Timestamp;
    buyerPrincipal: Principal;
}): Promise<{
    id: OrderId;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    rejectionReason?: string;
    productId: ProductId;
    paymentProofBlob?: ExternalBlob;
    updatedAt: Timestamp;
    buyerPrincipal: Principal;
}> {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n20(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n22(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rejectionReason)),
        productId: value.productId,
        paymentProofBlob: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.paymentProofBlob)),
        updatedAt: value.updatedAt,
        buyerPrincipal: value.buyerPrincipal
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    title: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    previewImageBlob: [] | [_ExternalBlob];
    isActive: boolean;
    category: _ProductCategory;
    fileStorageBlob: [] | [_ExternalBlob];
    priceUsd: bigint;
}): Promise<{
    id: ProductId;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    previewImageBlob?: ExternalBlob;
    isActive: boolean;
    category: ProductCategory;
    fileStorageBlob?: ExternalBlob;
    priceUsd: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        previewImageBlob: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.previewImageBlob)),
        isActive: value.isActive,
        category: from_candid_ProductCategory_n34(_uploadFile, _downloadFile, value.category),
        fileStorageBlob: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.fileStorageBlob)),
        priceUsd: value.priceUsd
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PendingVerification: null;
} | {
    Approved: null;
} | {
    Rejected: null;
}): OrderStatus {
    return "PendingVerification" in value ? OrderStatus.PendingVerification : "Approved" in value ? OrderStatus.Approved : "Rejected" in value ? OrderStatus.Rejected : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ABL: null;
} | {
    JazzCash: null;
}): PaymentMethod {
    return "ABL" in value ? PaymentMethod.ABL : "JazzCash" in value ? PaymentMethod.JazzCash : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    WebApp: null;
} | {
    Plugin: null;
} | {
    Script: null;
} | {
    Template: null;
} | {
    MobileApp: null;
}): ProductCategory {
    return "WebApp" in value ? ProductCategory.WebApp : "Plugin" in value ? ProductCategory.Plugin : "Script" in value ? ProductCategory.Script : "Template" in value ? ProductCategory.Template : "MobileApp" in value ? ProductCategory.MobileApp : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminAuditLog>): Array<AdminAuditLog> {
    return value.map((x)=>from_candid_AdminAuditLog_n14(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderView>): Promise<Array<OrderView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_OrderView_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductView>): Promise<Array<ProductView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ProductView_n32(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentMethod_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    ABL: null;
} | {
    JazzCash: null;
} {
    return value == PaymentMethod.ABL ? {
        ABL: null
    } : value == PaymentMethod.JazzCash ? {
        JazzCash: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    WebApp: null;
} | {
    Plugin: null;
} | {
    Script: null;
} | {
    Template: null;
} | {
    MobileApp: null;
} {
    return value == ProductCategory.WebApp ? {
        WebApp: null
    } : value == ProductCategory.Plugin ? {
        Plugin: null
    } : value == ProductCategory.Script ? {
        Script: null
    } : value == ProductCategory.Template ? {
        Template: null
    } : value == ProductCategory.MobileApp ? {
        MobileApp: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
